server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transactiondb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true