server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
            - id: wallet-service
              uri: lb://WALLET-SERVICE
              predicates:
                - Path=/wallets/**
            - id: transaction-service
              uri: lb://TRANSACTION-SERVICE
              predicates:
                - Path=/transactions/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
